<a href="https://colab.research.google.com/github/rokeyaislam1112/SQL-fundamental/blob/main/SQlite_databage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Create database
conn = sqlite3.connect("movies.db")

# Create Movies table
conn.execute("""
CREATE TABLE IF NOT EXISTS Movies (
    MovieID INTEGER,
    Title TEXT,
    Genre TEXT,
    ReleaseYear INTEGER,
    Rating REAL,
    BoxOfficeRevenue INTEGER,
    Director TEXT
)
""")


movies = [
    (1, 'Inception', 'Sci-Fi', 2010, 8.8, 830000000, 'Christopher Nolan'),
    (2, 'Titanic', 'Romance', 1997, 7.8, 2200000000, 'James Cameron'),
    (3, 'The Godfather', 'Crime', 1972, 9.2, 134000000, 'Francis Ford Coppola'),
    (4, 'Avatar', 'Sci-Fi', 2009, 7.9, 2840000000, 'James Cameron'),
    (5, 'Interstellar', 'Sci-Fi', 2014, 8.6, 677000000, 'Christopher Nolan'),
    (6, 'Parasite', 'Thriller', 2019, 8.6, 264000000, 'Bong Joon Ho'),
    (7, 'The Dark Knight', 'Action', 2008, 9.0, 1000000000, 'Christopher Nolan'),
    (8, "Schindler's List", 'Drama', 1993, 9.0, 322000000, 'Steven Spielberg'),
    (9, 'The Shawshank Redemption', 'Drama', 1994, 9.3, 283000000, 'Frank Darabont'),
    (10, 'Pulp Fiction', 'Crime', 1994, 8.9, 213000000, 'Quentin Tarantino')
]

conn.executemany("""
INSERT INTO Movies
VALUES (?, ?, ?, ?, ?, ?, ?)
""", movies)

conn.commit()

print("Movies table created successfully!")

Movies table created successfully!

In [ ]:
query = """
SELECT *
FROM Movies
WHERE Director = 'Christopher Nolan';
"""

pd.read_sql_query(query, conn)

,MovieID,Title,Genre,ReleaseYear,Rating,BoxOfficeRevenue,Director
0,1,Inception,Sci-Fi,2010,8.8,830000000,Christopher Nolan
1,5,Interstellar,Sci-Fi,2014,8.6,677000000,Christopher Nolan
2,7,The Dark Knight,Action,2008,9.0,1000000000,Christopher Nolan

In [ ]:
query = """
SELECT DISTINCT Genre
FROM Movies;
"""

pd.read_sql_query(query, conn)

      Genre
0    Sci-Fi
1   Romance
2     Crime
3  Thriller
4    Action
5     Drama

In [ ]:
query = """
SELECT Title, Rating
FROM Movies
ORDER BY Rating DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

                      Title  Rating
0  The Shawshank Redemption     9.3
1             The Godfather     9.2
2           The Dark Knight     9.0
3          Schindler's List     9.0
4              Pulp Fiction     8.9

In [ ]:
query = """
SELECT *
FROM Movies
WHERE ReleaseYear < 2000;
"""

pd.read_sql_query(query, conn)

,MovieID,Title,Genre,ReleaseYear,Rating,BoxOfficeRevenue,Director
0,2,Titanic,Romance,1997,7.8,2200000000,James Cameron
1,3,The Godfather,Crime,1972,9.2,134000000,Francis Ford Coppola
2,8,Schindler's List,Drama,1993,9.0,322000000,Steven Spielberg
3,9,The Shawshank Redemption,Drama,1994,9.3,283000000,Frank Darabont
4,10,Pulp Fiction,Crime,1994,8.9,213000000,Quentin Tarantino

In [ ]:
query = """
SELECT Genre, COUNT(*) AS TotalMovies
FROM Movies
GROUP BY Genre;
"""

pd.read_sql_query(query, conn)

      Genre  TotalMovies
0    Action            1
1     Crime            2
2     Drama            2
3   Romance            1
4    Sci-Fi            3
5  Thriller            1

In [ ]:
query = """
SELECT SUM(BoxOfficeRevenue) AS TotalRevenue
FROM Movies
WHERE Genre = 'Sci-Fi';
"""

pd.read_sql_query(query, conn)

   TotalRevenue
0    4347000000

In [ ]:
query = """
SELECT Title
FROM Movies
WHERE Rating > 8.5
AND Rating < 9.0;
"""

pd.read_sql_query(query, conn)

          Title
0     Inception
1  Interstellar
2      Parasite
3  Pulp Fiction

In [ ]:
query = """
SELECT Title
FROM Movies
WHERE Title LIKE '%The%';
"""

pd.read_sql_query(query, conn)

                      Title
0             The Godfather
1           The Dark Knight
2  The Shawshank Redemption

In [ ]:
query = """
SELECT Title, BoxOfficeRevenue
FROM Movies
ORDER BY BoxOfficeRevenue DESC
LIMIT 1;
"""

pd.read_sql_query(query, conn)

    Title  BoxOfficeRevenue
0  Avatar        2840000000

In [ ]:
query = """
SELECT AVG(Rating) AS AverageRating
FROM Movies
WHERE ReleaseYear > 2000;
"""

pd.read_sql_query(query, conn)

   AverageRating
0           8.58